### ISSUE TITLE
Learn IDE is not loading my lesson

### ISSUE THREAD

**Issue by chriskihlstrom** [learn-co-curriculum/first-ide-lab#2]
On my first day I am not getting a good impression of this course.  I have lost a lot of valuable time being unable to move forward with my lesson because of a bug.  My lesson will not open in learn IDE.

**Comment by kvignali** [comment]
hi @chriskihlstrom did you use Ask a Question to work with a Technical Coach to resolve this issue?

**Comment by chriskihlstrom** [comment]
Yes this issue was resolved a few days after it came up.
Thanks,
Chris
