### ISSUE TITLE
IDE directories missing

### ISSUE THREAD

**Issue by farradio** [learn-co-curriculum/first-ide-lab#38]
IDE is not showing any directories in the file tree besides: first-ide-lab-bootcamp-prep-000. There is also no 'Create New +' button at the bottom of the file tree.

**Comment by ihollander** [comment]
Hi there! This request sounds like an improvement to or a problem with the Learn platform.

Raising issues on GitHub, like you've done here should happen when there are problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can to clarify our error, and we will try to find a fix.
